apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
  namespace: default
spec:
  replicas: 2
  revisionHistorylimit: 2
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mynginx
        image: 683139589262.dkr.ecr.us-east-1.amazonaws.com/mynginx:6
        ports:
        - containerPort: 80
